from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name='login'),
    path('logout', Logout, name='logout'),
    path('register', Register, name='register'),
    path('return', previous_page, name='return'),
    path('customer/<int:customer_id>/Profile', Profile, name='profile-customer'),
    path('staff/<int:staff_id>/Profile', Profile, name='profile-staff'),
    path('customer/<int:customer_id>/change-password', ChangePassword, name='change-password-customer'),
    path('staff/<int:staff_id>/change-password', ChangePassword, name='change-password-staff'),
    path('terminate-account/<int:customer_id>', TerminateAccount, name='terminate-account'),
    path('customer/<int:customer_id>/Notifications', NotificationPage, name='notification-customer'),
    path('staff/<int:staff_id>/Notifications', NotificationPage, name='notification-staff'),
    path('clear-notifications/<int:customer_id>', ClearNotification, name='clear-notification-customer'),
    path('clear-notifications/<int:staff_id>', ClearNotification, name='clear-notification-staff'),
    path('notification-redirect/<int:notification_id>', NotificationRedirect, name='notification-redirect'),
    path('customer/<int:customer_id>/Appointments', CustomerPage, name='customer'),
    path('staff/<int:staff_id>/Appointments', StaffPage, name='staff'),
    path('staff/<int:staff_id>/make-appointment', MakeAppointmentStaff, name='make-appointment-staff'),
    path('medical-notes/<int:appointment_id>', MedicalNotes, name='medical-notes'),
    path('staff/<int:staff_id>/Slots', SlotPage, name='slot'),
    path('staff/<int:staff_id>/view-slot', ViewSlot, name='view-slot'),
    path('staff/<int:staff_id>/view-event', ViewEvent, name='view-event'),
    path('staff/<int:staff_id>/remove-slot/<int:slot_id>', RemoveSlot, name='remove-slot'),
    path('staff/<int:staff_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-staff'),
    path('staff/<int:staff_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-staff'),
    path('accept-reject-changes', AcceptRejectChanges, name='accept-reject-changes'),
    path('customer/<int:customer_id>/make-appointment', MakeAppointmentCustomer, name='make-appointment-customer'),
    path('customer/<int:customer_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-customer'),
    path('customer/<int:customer_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-customer'),
    path('customer/<int:customer_id>/History', HistoryPage, name='history'),
    path('customer/<int:customer_id>/view-history/<int:appointment_id>', ViewHistory, name='view-history'),
    path('customer/<int:customer_id>/Pets', PetPage, name='pet'),
    path('customer/<int:customer_id>/add-pet', AddPet, name='add-pet'),
    path('upload-pet-image/<int:customer_id>', UploadPetImage, name='upload-pet-image'),
    path('remove-pet-image/<int:customer_id>', RemovePetImage, name='remove-pet-image'),
    path('customer/<int:customer_id>/view-pet/<int:pet_id>', ViewPet, name='view-pet'),
    path('delete-pet-image/<int:customer_id>/<int:pet_id>', DeletePetImage, name='delete-pet-image'),
    path('Adopt-a-Pet', AdoptPage, name='adopt'),
    path('Adopt-a-Pet/view-animal/<int:pet_id>', ViewAdopt, name='view-adopt'),
    path('Adopt-a-Pet/register-animal', RegisterAdopt, name='register-adopt'),
    path('upload-adopt-image', UploadAdoptImage, name='upload-adopt-image'),
    path('remove-adopt-image', RemoveAdoptImage, name='remove-adopt-image'),
    path('delete-adopt-image/<int:pet_id>', DeleteAdoptImage, name='delete-adopt-image'),
    path('admin/<int:admin_id>/Staff', AdminPage, name='admin'),
    path('admin/<int:admin_id>/register-staff', RegisterStaff, name='register-staff'),
    path('admin/<int:admin_id>/view-staff/<str:staff_no>', ViewStaff, name='view-staff'),
    path('admin/<int:admin_id>/approve-customer', ApproveCustomer, name='approve-customer'),

    # JS query endpoints
    path('get-slots-staff', get_slots_staff, name='get-slots-staff'),
    path('get-slots-customer', get_slots_customer, name='get-slots-customer'),
    path('get-pets', get_pets, name='get-pets'),
]